### ISSUE TITLE
Investigate whether we can speed up operations on tabular data by using another backend

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Stdlib#196]
* [`pandas`](https://github.com/pandas-dev/pandas) v2.0.0 introduces [`pyarrow`](https://arrow.apache.org/docs/python/index.html) as a new backend, which is supposedly faster than `numpy`
* We could also use [`pyarrow`](https://arrow.apache.org/docs/python/index.html) directly
* We could also replace `pandas` by [`polars`](https://github.com/pola-rs/polars)

Generally, the interface of `polars` seems to be nicer to work with for us than `pandas`. They also do not have an [`index`](https://pola-rs.github.io/polars-book/user-guide/coming_from_pandas.html#polars-does-not-have-a-multi-indexindex), which is closer to our design, too.

## Tasks

- [ ] Back `Table` by `polars.DataFrame`
- [ ] Back `Row` by `polars.DataFrame`
- [ ] Back `Column` by `polars.Series`

**Comment by lars-reimann** [comment]
Overall, `polars` still needs some time to mature. If a column contains mixed data and no data type is specified explicitly, for example, it just silently replaces values with `None` that don't match the inferred type:

```py
import polars as pl

series = pl.Series("col", [1, "a", True, None])

for value in series:
    print(value)

# None
# a
# None
# None
```
